version: "3.8"

services:
  n8n:
    build: .
    image: n8n-with-ffmpeg
    container_name: n8n
    restart: always
    user: "root"
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_RESTRICT_FILE_ACCESS_TO=/data;/temp
    volumes:
      - ./n8n_data:/root/.n8n
      - ./assets:/data
      - ./temp:/temp

  ffmpeg-service:
    build: ./ffmpeg-service
    container_name: ffmpeg-service
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./assets:/data
      - ./temp:/temp

  whisper-service:
    build: ./whisper-service
    container_name: whisper-service
    restart: always
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
